const LOAD_USERS = 'LOAD_USERS';
const LOAD_POSTS = 'LOAD_POSTS';
const CHOOSE_USER = 'CHOOSE_USER';
const CHOOSE_POST = 'CHOOSE_POST';
const LOAD_COMMENTS = 'LOAD_COMMENTS';
const CHOOSE_COMMENT = 'CHOOSE_COMMENT';

export {
    LOAD_USERS,
    CHOOSE_USER,
    LOAD_POSTS,
    CHOOSE_POST,
    LOAD_COMMENTS,
    CHOOSE_COMMENT
}